# Generated by Django 3.2.3 on 2021-05-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ezLogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line", models.TextField(blank=True, null=True)),
                ("count", models.BigIntegerField(blank=True, null=True)),
                (
                    "logfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ezLogs.document",
                    ),
                ),
            ],
            options={"ordering": ["-count"]},
        ),
    ]
