# Generated by Django 3.2.3 on 2021-05-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ezLogs", "0002_logdetail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logdetail",
            options={"ordering": ["count"]},
        ),
    ]
