services:
    frontend:
        container_name: ezlogs-frontend
        build: ./frontend
        volumes:
            - ./frontend:/app
        ports:
            - "3000:3000"
        depends_on:
            - backend

    backend:
        container_name: ezlogs-backend
        build: .
        volumes:
            - .:/app
        ports:
            - 8000:8000
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULET_BACKEND=redis://redis:6379/0
            - ELASTIC_HOST=elasticsearch:9200
        depends_on:
            - redis
            - elasticsearch

    celery:
        container_name: ezlogs-celery
        build: .
        command: celery -A core worker -l INFO
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULET_BACKEND=redis://redis:6379/0
        depends_on:
            - redis

    redis:
        container_name: ezlogs-redis
        image: redis:alpine

    elasticsearch:
        container_name: ezlogs-elasticsearch
        image: elasticsearch:7.17.0
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node
